- name: catalogue configure
  hosts: catalogue
  become: yes

  tasks:
  - name: Enable Nodejs 20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install Nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: Create system user Roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"
  
  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading the catalogue application
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
      dest: /tmp/catalogue.zip
  
  - name: unzipping the catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app
  
  - name: copy catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load the products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  - name: start the catalogue service
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes
      

   
  
