# ansible-playbook -i inventory.ini -e instances=['mongodb', 'catalogue', 'redis', 'user', 'cart', 'mysql', 'shipping', 'rabbitmq', 'payment', 'frontend'] roboshop.yaml
- name: Create ec2 and R53 records
  hosts: all
  connection: local
  vars: 
    sg_id: sg-01625f1f03637676f
    ami_id: ami-0220d79f3f480ecf5
    domain_name: pvraolearns.online

    env: dev
    action: create 
    instances:
    - mongodb
    - catalogue
  
  tasks:
  - name: Create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create"

  - name: print the output 
    ansible.builtin.debug:
        msg: "{{ ec2_output }}"
    when: action == "create"

  
  - name: Create R53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" # mongodb-dev.pvraolearns.online, frontend-dev.pvraolearns.online
      type: A 
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    when: action == "create"

  - name: Create R53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.pvraolearns.online
      type: A 
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    when: # and 
    - item.item == "frontend"
    - action == "create"

  - name: Delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    when: action == "destroy"

  - name: Delete R53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}-{{ env }}.{{ domain_name }}" # roboshop-dev.pvraolearns.online
      type: A 
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"

